### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/Piefiller#1]
- [x] Automatically darken before drawing for contrast.
     - [x] Make it configurable.
- [x] Make default location/size in top left, some percentage of the window.
     - [x] Configurable!
- [x] Make all keybinds optional / toggleable or somesuch.
- [x] Make text show in a sorted, color-coded list next to the graph instead of around graph.
- [x] Specify default settings (step and depth, maybe others) in constructor.
- [x] Toggle visibility of profiler. Defaults to visible of course.
- [ ] Document what settings can be set and what they do.

**Comment by TangentFoxy** [comment]
Keybinds can be optional by passing an empty table to keys in the constructor. Edit: And actually, `setKey` does the same thing. I'm going to fix that though...

**Comment by TangentFoxy** [comment]
- [ ] Document how to make no keybinds available. (Which is to pass a nil/false to constructor or `setKey`.)
- [ ] Document background property.
- [x] ~~Document `original` mode vs `list` mode.~~ Abandoned original draw mode.
- [ ] Document or remove radius option in `draw` fn.

**Comment by TangentFoxy** [comment]
- [x] Step cannot go below 0
- [x] Depth cannot go below 1
- [x] lineJoin needs to be capped!

**Comment by TangentFoxy** [comment]
Scale is somehow not correctly a percentage of the window... o.o Otherwise, things work.
